Connect-PnPOnline -Url "https://indra365.sharepoint.com/sites/Grp_T_DN_Arquitetura_Solucoes_Multi_Praticas_QA" -UseWebLogin

Write-Host "`n=== Colaboradores_Aprovadores - ALL Column Names ===" -ForegroundColor Cyan
(Get-PnPField -List "Colaboradores_Aprovadores" | Select-Object -ExpandProperty InternalName) -join ", "

Write-Host "`n=== Solicitacoes_Ferias - Column Details ===" -ForegroundColor Cyan
Get-PnPField -List "Solicitacoes_Ferias" | Where-Object { $_.InternalName -notin @('ContentTypeId','_ModerationComments','File_x0020_Type','_ColorHex','_ColorTag','_Emoji','ComplianceAssetId','ContentType','_HasCopyDestinations','_CopySource','owshiddenversion','WorkflowVersion','_UIVersion','_UIVersionString','Attachments','_ModerationStatus','Edit','LinkTitleNoMenu','LinkTitle','LinkTitle2','SelectTitle','InstanceID','Order','GUID','WorkflowInstanceID','FileRef','FileDirRef','Last_x0020_Modified','Created_x0020_Date','FSObjType','SortBehavior','PermMask','PrincipalCount','FileLeafRef','UniqueId','ParentUniqueId','SyncClientId','ProgId','ScopeId','HTML_x0020_File_x0020_Type','_EditMenuTableStart','_EditMenuTableStart2','_EditMenuTableEnd','LinkFilenameNoMenu','LinkFilename','LinkFilename2','DocIcon','ServerUrl','EncodedAbsUrl','BaseName','MetaInfo','_Level','_IsCurrentVersion','ItemChildCount','FolderChildCount','Restricted','OriginatorId','NoExecute','ContentVersion','_ComplianceFlags','_ComplianceTag','_ComplianceTagWrittenTime','_ComplianceTagUserId','_IsRecord','AccessPolicy','_VirusStatus','_VirusVendorID','_VirusInfo','_RansomwareAnomalyMetaInfo','_DraftOwnerId','MainLinkSettings','AppAuthor','AppEditor','SMTotalSize','SMLastModifiedDate','SMTotalFileStreamSize','SMTotalFileCount','_CommentFlags','_CommentCount') } | Select-Object InternalName, TypeAsString | Format-Table -AutoSize

Write-Host "`n=== Saldo_Ferias - Column Details ===" -ForegroundColor Cyan
Get-PnPField -List "Saldo_Ferias" | Where-Object { $_.InternalName -notin @('ContentTypeId','_ModerationComments','File_x0020_Type','_ColorHex','_ColorTag','_Emoji','ComplianceAssetId','ContentType','_HasCopyDestinations','_CopySource','owshiddenversion','WorkflowVersion','_UIVersion','_UIVersionString','Attachments','_ModerationStatus','Edit','LinkTitleNoMenu','LinkTitle','LinkTitle2','SelectTitle','InstanceID','Order','GUID','WorkflowInstanceID','FileRef','FileDirRef','Last_x0020_Modified','Created_x0020_Date','FSObjType','SortBehavior','PermMask','PrincipalCount','FileLeafRef','UniqueId','ParentUniqueId','SyncClientId','ProgId','ScopeId','HTML_x0020_File_x0020_Type','_EditMenuTableStart','_EditMenuTableStart2','_EditMenuTableEnd','LinkFilenameNoMenu','LinkFilename','LinkFilename2','DocIcon','ServerUrl','EncodedAbsUrl','BaseName','MetaInfo','_Level','_IsCurrentVersion','ItemChildCount','FolderChildCount','Restricted','OriginatorId','NoExecute','ContentVersion','_ComplianceFlags','_ComplianceTag','_ComplianceTagWrittenTime','_ComplianceTagUserId','_IsRecord','AccessPolicy','_VirusStatus','_VirusVendorID','_VirusInfo','_RansomwareAnomalyMetaInfo','_DraftOwnerId','MainLinkSettings','AppAuthor','AppEditor','SMTotalSize','SMLastModifiedDate','SMTotalFileStreamSize','SMTotalFileCount','_CommentFlags','_CommentCount') } | Select-Object InternalName, TypeAsString | Format-Table -AutoSize
